import { ApiProperty } from "@nestjs/swagger";
import { Role } from "src/common/enum/roles.enum";
import { LocusMembersResponseDto } from "./locus-members.dto";



//This was generated by AI for saving some time)
export class LocusResponseDto {
    @ApiProperty({ description: 'The internal unique identifier for the locus', example: 1 })
    id: number;

    @ApiProperty({ description: 'The genome assembly version', example: 'GRCh38' })
    assemblyId: string;

    @ApiProperty({ description: 'The internal name of the locus', example: 'ENSG00000139618' })
    locusName: string;

    @ApiProperty({ description: 'The commonly used or public name for the locus', example: 'BRCA2' })
    publicLocusName: string;

    @ApiProperty({ description: 'The chromosome where the locus is located', example: '13' })
    chromosome: string;

    @ApiProperty({
        description: 'The DNA strand orientation: 1 for forward (+), -1 for reverse (-)',
        example: 1
    })
    strand: number;

    @ApiProperty({ description: 'The starting genomic coordinate', example: 32315474 })
    locusStart: number;

    @ApiProperty({ description: 'The ending genomic coordinate', example: 32400266 })
    locusStop: number;

    @ApiProperty({ description: 'The number of members associated with this locus', example: 5 })
    memberCount: number;

    @ApiProperty({description : 'Locus members'})
    locusMembers?:  LocusMembersResponseDto[]
}